// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/telemetry.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Metrics_Set_FullMethodName = "/telemetry.Metrics/Set"
)

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsClient interface {
	Set(ctx context.Context, in *SetMetricsRequest, opts ...grpc.CallOption) (*SetMetricsResponse, error)
}

type metricsClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsClient(cc grpc.ClientConnInterface) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) Set(ctx context.Context, in *SetMetricsRequest, opts ...grpc.CallOption) (*SetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMetricsResponse)
	err := c.cc.Invoke(ctx, Metrics_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServer is the server API for Metrics service.
// All implementations must embed UnimplementedMetricsServer
// for forward compatibility.
type MetricsServer interface {
	Set(context.Context, *SetMetricsRequest) (*SetMetricsResponse, error)
	mustEmbedUnimplementedMetricsServer()
}

// UnimplementedMetricsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsServer struct{}

func (UnimplementedMetricsServer) Set(context.Context, *SetMetricsRequest) (*SetMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedMetricsServer) mustEmbedUnimplementedMetricsServer() {}
func (UnimplementedMetricsServer) testEmbeddedByValue()                 {}

// UnsafeMetricsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServer will
// result in compilation errors.
type UnsafeMetricsServer interface {
	mustEmbedUnimplementedMetricsServer()
}

func RegisterMetricsServer(s grpc.ServiceRegistrar, srv MetricsServer) {
	// If the following call pancis, it indicates UnimplementedMetricsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Metrics_ServiceDesc, srv)
}

func _Metrics_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).Set(ctx, req.(*SetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Metrics_ServiceDesc is the grpc.ServiceDesc for Metrics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metrics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _Metrics_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/telemetry.proto",
}

const (
	MetricsMulti_Get_FullMethodName = "/telemetry.MetricsMulti/Get"
)

// MetricsMultiClient is the client API for MetricsMulti service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsMultiClient interface {
	Get(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetMetricsResponse], error)
}

type metricsMultiClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsMultiClient(cc grpc.ClientConnInterface) MetricsMultiClient {
	return &metricsMultiClient{cc}
}

func (c *metricsMultiClient) Get(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetMetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricsMulti_ServiceDesc.Streams[0], MetricsMulti_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetMetricsRequest, GetMetricsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsMulti_GetClient = grpc.ServerStreamingClient[GetMetricsResponse]

// MetricsMultiServer is the server API for MetricsMulti service.
// All implementations must embed UnimplementedMetricsMultiServer
// for forward compatibility.
type MetricsMultiServer interface {
	Get(*GetMetricsRequest, grpc.ServerStreamingServer[GetMetricsResponse]) error
	mustEmbedUnimplementedMetricsMultiServer()
}

// UnimplementedMetricsMultiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsMultiServer struct{}

func (UnimplementedMetricsMultiServer) Get(*GetMetricsRequest, grpc.ServerStreamingServer[GetMetricsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMetricsMultiServer) mustEmbedUnimplementedMetricsMultiServer() {}
func (UnimplementedMetricsMultiServer) testEmbeddedByValue()                      {}

// UnsafeMetricsMultiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsMultiServer will
// result in compilation errors.
type UnsafeMetricsMultiServer interface {
	mustEmbedUnimplementedMetricsMultiServer()
}

func RegisterMetricsMultiServer(s grpc.ServiceRegistrar, srv MetricsMultiServer) {
	// If the following call pancis, it indicates UnimplementedMetricsMultiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsMulti_ServiceDesc, srv)
}

func _MetricsMulti_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetricsMultiServer).Get(m, &grpc.GenericServerStream[GetMetricsRequest, GetMetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsMulti_GetServer = grpc.ServerStreamingServer[GetMetricsResponse]

// MetricsMulti_ServiceDesc is the grpc.ServiceDesc for MetricsMulti service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsMulti_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.MetricsMulti",
	HandlerType: (*MetricsMultiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _MetricsMulti_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/telemetry.proto",
}

const (
	BD_Ping_FullMethodName = "/telemetry.BD/Ping"
)

// BDClient is the client API for BD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BDClient interface {
	Ping(ctx context.Context, in *BDPingRequest, opts ...grpc.CallOption) (*BDPingResponse, error)
}

type bDClient struct {
	cc grpc.ClientConnInterface
}

func NewBDClient(cc grpc.ClientConnInterface) BDClient {
	return &bDClient{cc}
}

func (c *bDClient) Ping(ctx context.Context, in *BDPingRequest, opts ...grpc.CallOption) (*BDPingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BDPingResponse)
	err := c.cc.Invoke(ctx, BD_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BDServer is the server API for BD service.
// All implementations must embed UnimplementedBDServer
// for forward compatibility.
type BDServer interface {
	Ping(context.Context, *BDPingRequest) (*BDPingResponse, error)
	mustEmbedUnimplementedBDServer()
}

// UnimplementedBDServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBDServer struct{}

func (UnimplementedBDServer) Ping(context.Context, *BDPingRequest) (*BDPingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBDServer) mustEmbedUnimplementedBDServer() {}
func (UnimplementedBDServer) testEmbeddedByValue()            {}

// UnsafeBDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BDServer will
// result in compilation errors.
type UnsafeBDServer interface {
	mustEmbedUnimplementedBDServer()
}

func RegisterBDServer(s grpc.ServiceRegistrar, srv BDServer) {
	// If the following call pancis, it indicates UnimplementedBDServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BD_ServiceDesc, srv)
}

func _BD_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BDPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BDServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BD_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BDServer).Ping(ctx, req.(*BDPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BD_ServiceDesc is the grpc.ServiceDesc for BD service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BD_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.BD",
	HandlerType: (*BDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _BD_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/telemetry.proto",
}
