// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/telemetry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mtype int32

const (
	Mtype_GAUGE   Mtype = 0
	Mtype_COUNTER Mtype = 1
)

// Enum value maps for Mtype.
var (
	Mtype_name = map[int32]string{
		0: "GAUGE",
		1: "COUNTER",
	}
	Mtype_value = map[string]int32{
		"GAUGE":   0,
		"COUNTER": 1,
	}
)

func (x Mtype) Enum() *Mtype {
	p := new(Mtype)
	*p = x
	return p
}

func (x Mtype) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mtype) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_telemetry_proto_enumTypes[0].Descriptor()
}

func (Mtype) Type() protoreflect.EnumType {
	return &file_proto_telemetry_proto_enumTypes[0]
}

func (x Mtype) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mtype.Descriptor instead.
func (Mtype) EnumDescriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{0}
}

type MetricsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string][]byte      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsList) Reset() {
	*x = MetricsList{}
	mi := &file_proto_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsList) ProtoMessage() {}

func (x *MetricsList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsList.ProtoReflect.Descriptor instead.
func (*MetricsList) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsList) GetValues() map[string][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type SetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []byte                 `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMetricsRequest) Reset() {
	*x = SetMetricsRequest{}
	mi := &file_proto_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMetricsRequest) ProtoMessage() {}

func (x *SetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMetricsRequest.ProtoReflect.Descriptor instead.
func (*SetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *SetMetricsRequest) GetValues() []byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type SetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMetricsResponse) Reset() {
	*x = SetMetricsResponse{}
	mi := &file_proto_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMetricsResponse) ProtoMessage() {}

func (x *SetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMetricsResponse.ProtoReflect.Descriptor instead.
func (*SetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *SetMetricsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mtype         Mtype                  `protobuf:"varint,1,opt,name=mtype,proto3,enum=telemetry.Mtype" json:"mtype,omitempty"`
	Id            []string               `protobuf:"bytes,2,rep,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_proto_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *GetMetricsRequest) GetMtype() Mtype {
	if x != nil {
		return x.Mtype
	}
	return Mtype_GAUGE
}

func (x *GetMetricsRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mtype         Mtype                  `protobuf:"varint,1,opt,name=mtype,proto3,enum=telemetry.Mtype" json:"mtype,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_proto_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *GetMetricsResponse) GetMtype() Mtype {
	if x != nil {
		return x.Mtype
	}
	return Mtype_GAUGE
}

func (x *GetMetricsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMetricsResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type BDPingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BDPingRequest) Reset() {
	*x = BDPingRequest{}
	mi := &file_proto_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BDPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BDPingRequest) ProtoMessage() {}

func (x *BDPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BDPingRequest.ProtoReflect.Descriptor instead.
func (*BDPingRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{5}
}

type BDPingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BDPingResponse) Reset() {
	*x = BDPingResponse{}
	mi := &file_proto_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BDPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BDPingResponse) ProtoMessage() {}

func (x *BDPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BDPingResponse.ProtoReflect.Descriptor instead.
func (*BDPingResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *BDPingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_telemetry_proto protoreflect.FileDescriptor

const file_proto_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x15proto/telemetry.proto\x12\ttelemetry\"\x84\x01\n" +
	"\vMetricsList\x12:\n" +
	"\x06values\x18\x01 \x03(\v2\".telemetry.MetricsList.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"+\n" +
	"\x11SetMetricsRequest\x12\x16\n" +
	"\x06values\x18\x02 \x01(\fR\x06values\"*\n" +
	"\x12SetMetricsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"K\n" +
	"\x11GetMetricsRequest\x12&\n" +
	"\x05mtype\x18\x01 \x01(\x0e2\x10.telemetry.MtypeR\x05mtype\x12\x0e\n" +
	"\x02id\x18\x02 \x03(\tR\x02id\"b\n" +
	"\x12GetMetricsResponse\x12&\n" +
	"\x05mtype\x18\x01 \x01(\x0e2\x10.telemetry.MtypeR\x05mtype\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\x0f\n" +
	"\rBDPingRequest\"&\n" +
	"\x0eBDPingResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error*\x1f\n" +
	"\x05Mtype\x12\t\n" +
	"\x05GAUGE\x10\x00\x12\v\n" +
	"\aCOUNTER\x10\x012M\n" +
	"\aMetrics\x12B\n" +
	"\x03Set\x12\x1c.telemetry.SetMetricsRequest\x1a\x1d.telemetry.SetMetricsResponse2T\n" +
	"\fMetricsMulti\x12D\n" +
	"\x03Get\x12\x1c.telemetry.GetMetricsRequest\x1a\x1d.telemetry.GetMetricsResponse0\x012A\n" +
	"\x02BD\x12;\n" +
	"\x04Ping\x12\x18.telemetry.BDPingRequest\x1a\x19.telemetry.BDPingResponseB\x11Z\x0ftelemetry/protob\x06proto3"

var (
	file_proto_telemetry_proto_rawDescOnce sync.Once
	file_proto_telemetry_proto_rawDescData []byte
)

func file_proto_telemetry_proto_rawDescGZIP() []byte {
	file_proto_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)))
	})
	return file_proto_telemetry_proto_rawDescData
}

var file_proto_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_telemetry_proto_goTypes = []any{
	(Mtype)(0),                 // 0: telemetry.Mtype
	(*MetricsList)(nil),        // 1: telemetry.MetricsList
	(*SetMetricsRequest)(nil),  // 2: telemetry.SetMetricsRequest
	(*SetMetricsResponse)(nil), // 3: telemetry.SetMetricsResponse
	(*GetMetricsRequest)(nil),  // 4: telemetry.GetMetricsRequest
	(*GetMetricsResponse)(nil), // 5: telemetry.GetMetricsResponse
	(*BDPingRequest)(nil),      // 6: telemetry.BDPingRequest
	(*BDPingResponse)(nil),     // 7: telemetry.BDPingResponse
	nil,                        // 8: telemetry.MetricsList.ValuesEntry
}
var file_proto_telemetry_proto_depIdxs = []int32{
	8, // 0: telemetry.MetricsList.values:type_name -> telemetry.MetricsList.ValuesEntry
	0, // 1: telemetry.GetMetricsRequest.mtype:type_name -> telemetry.Mtype
	0, // 2: telemetry.GetMetricsResponse.mtype:type_name -> telemetry.Mtype
	2, // 3: telemetry.Metrics.Set:input_type -> telemetry.SetMetricsRequest
	4, // 4: telemetry.MetricsMulti.Get:input_type -> telemetry.GetMetricsRequest
	6, // 5: telemetry.BD.Ping:input_type -> telemetry.BDPingRequest
	3, // 6: telemetry.Metrics.Set:output_type -> telemetry.SetMetricsResponse
	5, // 7: telemetry.MetricsMulti.Get:output_type -> telemetry.GetMetricsResponse
	7, // 8: telemetry.BD.Ping:output_type -> telemetry.BDPingResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_telemetry_proto_init() }
func file_proto_telemetry_proto_init() {
	if File_proto_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_telemetry_proto_depIdxs,
		EnumInfos:         file_proto_telemetry_proto_enumTypes,
		MessageInfos:      file_proto_telemetry_proto_msgTypes,
	}.Build()
	File_proto_telemetry_proto = out.File
	file_proto_telemetry_proto_goTypes = nil
	file_proto_telemetry_proto_depIdxs = nil
}
